remove frun from the test. fix for csh.

diff --git a/tools/bin/FAX-run-test b/tools/bin/FAX-run-test
--- a/tools/bin/FAX-run-test
+++ b/tools/bin/FAX-run-test
@@ -99,27 +99,27 @@ else
 fi
 
 
-
-get_response  "This test will send an frun job to be executed on the grid, would you like to proceed?";
-
-if [ $do = "y" ]
-then
-    kom="frun -v --inDS=user.ilijav.HCtest.1 --exec \"echo %IN > input.txt\" --athenaTag=17.2.0 --noBuild --outputs=input.txt --outDS=user.ivukotic.HCtestREWRITTEN.1 --site=ANALY_CERN_XROOTD "
-    printf "Executing command:\n%s\n---------------------------------------------------------------------------------------------------------\n" "$kom"
-    eval $kom
-    if [ "$?" -eq 0 ]
-    then
-        echo "TEST RESULT - OK"
-        res=0$res
-    else
-        echo "TEST RESULT - FAIL"
-        res=1$res
-    fi
-    echo "========================================================================================================"
-else
-    echo "Skipping this test."
-    res=x$res
-fi
+# 
+# get_response  "This test will send an frun job to be executed on the grid, would you like to proceed?";
+# 
+# if [ $do = "y" ]
+# then
+#     kom="frun -v --inDS=user.ilijav.HCtest.1 --exec \"echo %IN > input.txt\" --athenaTag=17.2.0 --noBuild --outputs=input.txt --outDS=user.ivukotic.HCtestREWRITTEN.1 --site=ANALY_CERN_XROOTD "
+#     printf "Executing command:\n%s\n---------------------------------------------------------------------------------------------------------\n" "$kom"
+#     eval $kom
+#     if [ "$?" -eq 0 ]
+#     then
+#         echo "TEST RESULT - OK"
+#         res=0$res
+#     else
+#         echo "TEST RESULT - FAIL"
+#         res=1$res
+#     fi
+#     echo "========================================================================================================"
+# else
+#     echo "Skipping this test."
+#     res=x$res
+# fi
 
 echo "Uploading test results..."
 java -jar $SCRIPTPATH/FAX2Google-0.0.2-jar-with-dependencies.jar $res > /dev/null
